// This file is part of the re-motion Core Framework (www.re-motion.org)
// Copyright (C) 2005-2009 rubicon informationstechnologie gmbh, www.rubicon.eu
// 
// The re-motion Core Framework is free software; you can redistribute it 
// and/or modify it under the terms of the GNU Lesser General Public License 
// version 3.0 as published by the Free Software Foundation.
// 
// re-motion is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with re-motion; if not, see http://www.gnu.org/licenses.
// 
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Remotion.Data.Linq.Clauses;
using Remotion.Data.Linq.Parsing.ExpressionTreeVisitors;
using Remotion.Utilities;

namespace Remotion.Data.Linq.Parsing.Structure.IntermediateModel
{
  /// <summary>
  /// Represents a <see cref="MethodCallExpression"/> for 
  /// <see cref="Queryable.Select{TSource,TResult}(System.Linq.IQueryable{TSource},System.Linq.Expressions.Expression{System.Func{TSource,TResult}})"/>.
  /// It is generated by <see cref="ExpressionTreeParser"/> when an <see cref="Expression"/> tree is parsed.
  /// </summary>
  public class SelectExpressionNode : MethodCallExpressionNodeBase
  {
    public static readonly MethodInfo[] SupportedMethods = new[]
                                                           {
                                                               GetSupportedMethod (() => Queryable.Select<object, object> (null, o => null))
                                                           };

    private Expression _cachedSelector;

    public SelectExpressionNode (MethodCallExpressionParseInfo parseInfo, LambdaExpression selector)
        : base (parseInfo)
    {
      ArgumentUtility.CheckNotNull ("selector", selector);

      if (selector != null && selector.Parameters.Count != 1)
        throw new ArgumentException ("Selector must have exactly one parameter.", "selector");

      Selector = selector;
    }

    public LambdaExpression Selector { get; private set; }

    public Expression GetResolvedSelector (QuerySourceClauseMapping querySourceClauseMapping)
    {
      ArgumentUtility.CheckNotNull ("querySourceClauseMapping", querySourceClauseMapping);

      if (_cachedSelector == null)
      {
        _cachedSelector = Source.Resolve (Selector.Parameters[0], Selector.Body, querySourceClauseMapping);
        _cachedSelector = TransparentIdentifierRemovingVisitor.ReplaceTransparentIdentifiers (_cachedSelector);
      }

      return _cachedSelector;
    }

    public override Expression Resolve (ParameterExpression inputParameter, Expression expressionToBeResolved, QuerySourceClauseMapping querySourceClauseMapping)
    {
      ArgumentUtility.CheckNotNull ("inputParameter", inputParameter);
      ArgumentUtility.CheckNotNull ("expressionToBeResolved", expressionToBeResolved);
      ArgumentUtility.CheckNotNull ("querySourceClauseMapping", querySourceClauseMapping);

      // we modify the structure of the stream of data coming into this node by our selector,
      // so we first resolve the selector, then we substitute the result for the inputParameter in the expressionToBeResolved
      var resolvedSelector = GetResolvedSelector(querySourceClauseMapping);
      return ReplacingVisitor.Replace (inputParameter, resolvedSelector, expressionToBeResolved);
    }

    public override ParameterExpression CreateParameterForOutput ()
    {
      // we modify the structure of the stream of data coming into this node by our selector,
      // so we create a parameter capable of holding the modified stream elements
      return Expression.Parameter (Selector.Body.Type, AssociatedIdentifier);
    }

    public override IClause CreateClause (IClause previousClause, QuerySourceClauseMapping querySourceClauseMapping)
    {
      ArgumentUtility.CheckNotNull ("previousClause", previousClause);
      ArgumentUtility.CheckNotNull ("querySourceClauseMapping", querySourceClauseMapping);
      
      return new SelectClause (previousClause, Selector, GetResolvedSelector (querySourceClauseMapping));
    }
  }
}