// This file is part of the re-motion Core Framework (www.re-motion.org)
// Copyright (C) 2005-2009 rubicon informationstechnologie gmbh, www.rubicon.eu
// 
// The re-motion Core Framework is free software; you can redistribute it 
// and/or modify it under the terms of the GNU Lesser General Public License 
// version 3.0 as published by the Free Software Foundation.
// 
// re-motion is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with re-motion; if not, see http://www.gnu.org/licenses.
// 
using System;
using Remotion.Data.Linq.Clauses.Expressions;

namespace Remotion.Data.Linq.Clauses
{
  /// <summary>
  /// Represents a clause in a <see cref="QueryModel"/>'s <see cref="QueryModel.BodyClauses"/> collection. Body clauses take the items generated by 
  /// the <see cref="QueryModel.MainFromClause"/>, filtering (<see cref="WhereClause"/>), ordering (<see cref="OrderByClause"/>), augmenting 
  /// (<see cref="AdditionalFromClause"/>), or otherwise processing them before they are passed to the <see cref="QueryModel.SelectOrGroupClause"/>.
  /// </summary>
  public interface IBodyClause : IClause
  {
    /// <summary>
    /// Accepts the specified visitor by calling one of its Visit... methods.
    /// </summary>
    /// <param name="visitor">The visitor to accept.</param>
    /// <param name="queryModel">The query model in whose context this clause is visited.</param>
    /// <param name="index">The index of this clause in the <paramref name="queryModel"/>'s <see cref="QueryModel.BodyClauses"/> collection.</param>
    void Accept (IQueryModelVisitor visitor, QueryModel queryModel, int index);

    /// <summary>
    /// Clones this clause, adjusting all <see cref="QuerySourceReferenceExpression"/> instances held by it as defined by
    /// <paramref name="cloneContext"/>.
    /// </summary>
    /// <param name="cloneContext">The clone context to use for replacing <see cref="QuerySourceReferenceExpression"/> objects.</param>
    /// <returns>A clone of this clause.</returns>
    IBodyClause Clone (CloneContext cloneContext);
  }
}