using System;

namespace Remotion.Data.Linq.Clauses
{
  public interface IQuerySource
  {
    /// <summary>
    /// Gets or sets a name describing the items generated by this <see cref="IQuerySource"/>.
    /// </summary>
    string ItemName { get; }
  }
}